defaults:
  - _self_
  - task@_global_: PointMaze_MediumDense
  - agent@_global_: taco
  - override hydra/launcher: submitit_local

domain: gym
# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
random_init: true
random_goal: false
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 5000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 500000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
resolution: 84
save_video: False
save_train_video: False
use_tb: True
use_wandb: True
# wandb
wandb_project: "taco_gym"
wandb_entity: "taco"
wandb_tag: none
wandb_run_name: ${now:%Y.%m.%d}_${now:%H%M}_cdmc_${task_name}
wandb_id: none # needed for resuming runs

# experiment
experiment: exp
checkpoint: False 
# agent
lr: 1e-4
encoder_lr: 1e-4
feature_dim: 50
exp_name: default


hydra:
  run:
    dir: ./exp_local/${exp_name}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm